apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels: 
    app: api-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-container 
        image: israel.azurecr.io/api-gateway/master:9e1523c
        ports:
        - name: api-port
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: kd-config
              optional: true
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: keyforaks 