apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels: 
    app: auth-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-container 
        image: israel.azurecr.io/authentication-service/master:37a2610
        ports:
        - name: auth-port
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: kd-config
              optional: true
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: keyforaks 