apiVersion: apps/v1
kind: Deployment
metadata:
  name: delegation-deployment
  labels: 
    app: delegation-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delegation-service
  template:
    metadata:
      labels:
        app: delegation-service
    spec:
      containers:
      - name: delegation-container 
        image: israel.azurecr.io/delegation-service/master:133164d
        ports:
        - name: delegation-ports
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: kd-config
              optional: true
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: keyforaks 