apiVersion: apps/v1
kind: Deployment
metadata:
  name: drive-deployment
  labels: 
    app: drive-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drive-service
  template:
    metadata:
      labels:
        app: drive-service
    spec:
      containers:
      - name: drive-container 
        image: israel.azurecr.io/drive-ui/master:38121da
        ports:
        - name: drive-port
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: kd-config
              optional: true
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: keyforaks 