apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-deployment
  labels: 
    app: file-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
      - name: file-container 
        image: israel.azurecr.io/file-service/develop:latest
        ports:
        - name: file-port
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: kd-config
              optional: true
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: keyforaks   
       