apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission-deployment
  labels: 
    app: permission-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: permission-service
  template:
    metadata:
      labels:
        app: permission-service
    spec:
      containers:
      - name: permission-container 
        image: israel.azurecr.io/permission-service/master:769171f
        ports:
        - name: permision-port
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: kd-config
              optional: true
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: keyforaks