apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  labels: 
    app: search-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-container 
        image: israel.azurecr.io/search-service/develop:latest
        ports:
        - name: search-ports
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: kd-config
              optional: true
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: keyforaks