apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-deployment
  labels: 
    app: socket-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-service
  template:
    metadata:
      labels:
        app: socket-service
    spec:
      containers:
      - name: socket-container 
        image: israel.azurecr.io/socket-service/develop:latest
        ports:
        - name: socket-port
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: kd-config
              optional: true
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: keyforaks 
