apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-deployment
  labels: 
    app: spike-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spike-service
  template:
    metadata:
      labels:
        app: spike-service
    spec:
      containers:
      - name: spike-container 
        image: israel.azurecr.io/spike-service/master:bd69af0
        ports:
        - name: spike-ports
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: kd-config
              optional: true
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: keyforaks   
