apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
  labels: 
    app: upload-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      containers:
      - name: upload-container 
        image: israel.azurecr.io/upload-service/master:1d1fb04
        ports:
        - name: upload-ports
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: kd-config
              optional: true
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: keyforaks  