apiVersion: v1
kind: ConfigMap
metadata:
  name: kd-config
  namespace: default
data:
  AUDIENCE: 0mBMe5vYJyuFtvHpEWVDPumqaVl~xr
  BIND_ADDRESS: 0.0.0.0:8080
  CLIENT_ENDPOINT: /
  DEBUG_MODE: "true"
  DEFAULT_LISTEN_PORT: "8080"
  DEFAULT_WAIT_TIMEOUT: "30"
  DEL_PROT: "8080"
  DEL_SPIKE_REQUIRED: "false"
  DISABLE_GOOGLE_CHROME: "1"
  DOMAINUSERS_QUERY: nonExternals
  DS_SERVICE_NAME: download-service
  ELASTIC_APM_ACTIVE: "true"
  ELASTIC_APM_CAPTURE_BODY: all
  ELASTIC_APM_CAPTURE_HEADERS: "true"
  ELASTIC_APM_ENVIRONMENT: production
  ELASTIC_APM_IGNORE_URLS: /grpc.health.v1.Health/Check,/api/healthcheck
  ELASTIC_APM_METRICS_INTERVAL: 10s
  ELASTIC_APM_SERVER_URL: http://52.169.68.115:8200
  ELASTICSEARCH_URL: http://13.94.118.192:9200,http://52.169.68.115:9200,http://52.169.114.42:9200
  ENVIRONMENT: production
  FS_AUTO_INDEX: "true"
  GIN_MODE: release
  GW_ALLOW_ORIGINS: http://shahar.northeurope.cloudapp.azure.com*
  GW_API_ROUTE: /api
  GW_APPROVAL_URL: http://23.102.32.203/api/v1/request
  GW_AUTH_URL: /auth/login
  GW_DELEGATION_SERVICE: delegation-service:8080
  GW_DOCS_URL: http://13.79.160.153:3000/api/files
  GW_DOWNLOAD_SERVICE: download-service:8080
  GW_ENABLE_EXTERNAL_SHARE: "true"
  GW_EXTERNAL_APM_URL: http://52.169.68.115:8200
  GW_EXTERNAL_SHARE_NAME: שתף עם חוצן
  GW_FILE_SERVICE: file-service:8080
  GW_GOTENBERG_SERVICE: http://gotenberg:8080
  GW_MY_EXTERNAL_SHARES_NAME: שותף עם חוצן
  GW_PERMISSION_SERVICE: permission-service:8080
  GW_PORT: "8080"
  GW_SEARCH_SERVICE: search-service:8080
  GW_SECRET: krypton@drive
  GW_UPLOAD_SERVICE: upload-service:8080
  GW_WEB_UI: http://shahar.northeurope.cloudapp.azure.com
  HOST_NAME: permit-service
  KARTOFFEL_URL: http://kartoffel-master.eastus.cloudapp.azure.com:3001
  LOG_INDEX: kdrive
  LOG_LEVEL: INFO
  MONGO_CLIENT_CONNECTION_TIMEOUT: "10"
  MONGO_CLIENT_PING_TIMEOUT: "10"
  MONGO_HOST: mongodb://168.63.40.248:27017/shahar-DB
  MONGODB_NAME: shraga-proxy
  MONGODB_URL: mongodb://168.63.40.248:27017
  NODE_ENV: prod
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  PHONE_BOOK_URL: http://phonebook.dropbox.rabaz.org
  PMTS_APPROVAL_URL: http://23.102.32.203/api/v1/request
  PMTS_AUDIENCE: _LCF5avgIpoXSWhY5Jl8mMi0Q~4_~R
  PMTS_ELASTIC_APM_IGNORE_URLS: /grpc.health.v1.Health/Check
  PMTS_GRANT_TYPE: client_credentials
  PMTS_MONGO_HOST: mongodb://168.63.40.248:27017/shahar-permit
  PMTS_PORT: "8080"
  PMTS_SPIKE_SERVICE: spike-service:8080
  PS_ELASTIC_APM_ACTIVE: "true"
  PS_ELASTIC_APM_ENVIRONMENT: production
  PS_ELASTIC_APM_IGNORE_URLS: /grpc.health.v1.Health/Check,/api/healthcheck
  PS_ELASTIC_APM_SERVER_URL: http://52.169.68.115:8200
  PS_ELASTICSEARCH_URL: http://13.94.118.192:9200,http://52.169.68.115:9200,http://52.169.114.42:9200
  PS_MONGO_HOST: mongodb://168.63.40.248:27017/shahar-permission
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_URL: redis://redis:6379
  RPC_PORT: "8080"
  S3_ACCESS_KEY: kdqastrg
  S3_ENDPOINT: http://40.112.95.75:8000
  S3_SECRET_KEY: qUO0pMe0wHyLfn0+w2x+55jE8cW7Os+H2mwU2gmzARCzPfkFkmXKOYbN0l5baktuRZ1T3qzXm1KyNoBNBm9big==
  SAML_CALLBACK_URL: /auth/metadata.xml/callback
  SAML_ENTRY_POINT: /simplesaml/saml2/idp/SSOService.php
  SAML_ISSUER: /auth/metadata.xml
  SECRET_KEY: krypton@drive
  SESSION_SECRET: Secret
  SHRAGA_URL: http://13.79.7.3
  SIMPLESAMLPHP_ADMIN_PASSWORD: test
  SIMPLESAMLPHP_SECRET_SALT: salt
  SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: /auth/metadata.xml/callback
  SIMPLESAMLPHP_SP_ENTITY_ID: /auth/metadata.xml
  SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: /auth/logout
  SPIKE_AUTH_SERVER_PORT: "1337"
  SPIKE_CLIENT_ID: EPBpjCiczupCXZgBEq3ARZCinUt4LSXtOsVrI1Ub
  SPIKE_CLIENT_SECRET: u5qxEK0sy17ReZ7t8aVeN1gCcdI9hRiM78i9J_9Z6jA2YWcvbgczcchKqZ4WnXOsdT6jxmuVCLC3~RXuVcE5EsOG4JJi~B8AJQSB
  SPIKE_PUBLIC_KEY_FULL_PATH: /usr/src/app/publickey.pem
  SPIKE_REQUIRED: "true"
  SPIKE_TOKEN_URL: https://spike.westeurope.cloudapp.azure.com:1337/oauth2/token
  SPIKE_URL: https://spike.westeurope.cloudapp.azure.com
  SS_ELASTIC_APM_IGNORE_URLS: /grpc.health.v1.Health/Check
  SS_ELASTICSEARCH_INDEX: shahar-files
  SS_ELASTICSEARCH_URL: http://13.94.118.192:9200,http://52.169.68.115:9200,http://52.169.114.42:9200
  SS_HEALTH_CHECK_INTERVAL: "5"
  SS_PORT: "8080"
  STRATEGY: shraga
  TCP_PORT: "8080"
  TOKEN_ID: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJrYXJ0b2ZmZWwiLCJzdWIiOiI1ZDc2NTA2NTBmYWY2ODIwOTQ4YzMzZGQiLCJzY29wZSI6W10sImNsaWVudElkIjoiRVBCcGpDaWN6dXBDWFpnQkVxM0FSWkNpblV0NExTWHRPc1ZySTFVYiIsImlhdCI6MTU2ODIxMDM1NSwiZXhwIjoxNTY4MjEwNTM1LCJpc3MiOiJodHRwczovLzUxLjE0NC4xNzguMTIxIn0.bSALlqft4U_FiiPr8gtYxx1AOVmnwMxN9-ardt5FhaY_UhKc18PIq5dBSMCMp34sfZnwsBh7uxL3wxDjPxZzYb_RMyLc_wonUurdDjI9zBq5fkyhwdNdBxIirBooVMwjt3mqxVtvVSsWvip3Lfj0zW-qb7n_n5LDRI4YG36cfUc_FCA60keccyHGMJJ1jd8trTvx1XQT8-PTlOlIQifws42Hpc3KIAUM0a2K-VuhK8bdQgcnvkB9Ca55OstOFi27cFf1jV9VO1as5yA6WabDTxht5KxfVN-nMpHhQN0CFw-kngIX2P8F0rlmA2JwmSPVcnDF3OweMAs5CBHQzkdomA
  USER_KARTOFFEL_AUDIENCE: kartoffel
  USERS_RPC_ENDPOINT: user-service:8080
  USR_MONGO_HOST: mongodb://168.63.40.248:27017/shaharDB
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-05T12:37:27Z"
  name: kd-config
  namespace: default
  resourceVersion: "7846420"
  selfLink: /api/v1/namespaces/default/configmaps/kd-config
  uid: 8808c35a-d965-4d0d-9ce2-a69170c1ba69


